### ISSUE TITLE
VTK build failing

### ISSUE THREAD

**Issue by cmaurini** [hashdist/hashdist#307]
I have an error at the compilation of vtk. I am on a rhel5 cluster and I use gcc482. 
Please find here the [build.log](http://www.lmm.jussieu.fr/~corrado/tmp/build.log)

**Comment by certik** [comment]
Thanks @cmaurini for the report. The error is:
```
2015/02/20 00:32:36 - INFO: [package:run_job] [ 90%] Building CXX object Widgets/CMakeFiles/vtkWidgetsPythonD.dir/vtkBiDimensionalRepresentation2DPython.cxx.o
2015/02/20 00:32:36 - INFO: [package:run_job] [ 90%] Building CXX object Infovis/CMakeFiles/vtkInfovis.dir/vtkTimePointToString.cxx.o
2015/02/20 00:32:37 - INFO: [package:run_job] [ 90%] Building CXX object Widgets/CMakeFiles/vtkWidgetsPythonD.dir/vtkBiDimensionalWidgetPython.cxx.o
2015/02/20 00:32:37 - INFO: [package:run_job] [ 90%] Building CXX object Widgets/CMakeFiles/vtkWidgetsPythonD.dir/vtkBorderRepresentationPython.cxx.o
2015/02/20 00:32:37 - INFO: [package:run_job] [ 90%] Building CXX object Widgets/CMakeFiles/vtkWidgetsPythonD.dir/vtkBorderWidgetPython.cxx.o
2015/02/20 00:32:37 - INFO: [package:run_job] [ 90%] Building CXX object Infovis/CMakeFiles/vtkInfovis.dir/vtkInfovisInstantiator.cxx.o
2015/02/20 00:32:37 - INFO: [package:run_job] [ 90%] Building CXX object Widgets/CMakeFiles/vtkWidgetsPythonD.dir/vtkBoundedPlanePointPlacerPython.cxx.o
2015/02/20 00:32:37 - INFO: [package:run_job] [ 90%] Building CXX object Widgets/CMakeFiles/vtkWidgetsPythonD.dir/vtkBoxRepresentationPython.cxx.o
2015/02/20 00:32:37 - INFO: [package:run_job] [ 90%] Building CXX object Widgets/CMakeFiles/vtkWidgetsPythonD.dir/vtkBoxWidgetPython.cxx.o
2015/02/20 00:32:38 - INFO: [package:run_job] Linking CXX shared library ../bin/libvtkInfovis.so
2015/02/20 00:32:38 - INFO: [package:run_job] [ 90%] Building CXX object Widgets/CMakeFiles/vtkWidgetsPythonD.dir/vtkBoxWidget2Python.cxx.o
2015/02/20 00:32:38 - INFO: [package:run_job] [ 90%] /usr/bin/ld: CMakeFiles/vtkInfovis.dir/vtkMultiCorrelativeStatistics.cxx.o: relocation R_X86_64_PC32 against `_ZNSt6vectorIP12vtkDataArraySaIS1_EE13_M_insert_auxEN9__gnu_cxx17__normal_iteratorIPS1_S3_EERKS1_' can not be used when making a shared object; recompile with -fPIC
2015/02/20 00:32:38 - INFO: [package:run_job] /usr/bin/ld: final link failed: Bad value
2015/02/20 00:32:38 - INFO: [package:run_job] collect2: error: ld returned 1 exit status
2015/02/20 00:32:38 - INFO: [package:run_job] gmake[2]: *** [bin/libvtkInfovis.so.5.10.1] Error 1
2015/02/20 00:32:38 - INFO: [package:run_job] Building CXX object Widgets/CMakeFiles/vtkWidgetsPythonD.dir/vtkBrokenLineWidgetPython.cxx.o
2015/02/20 00:32:38 - INFO: [package:run_job] gmake[1]: *** [Infovis/CMakeFiles/vtkInfovis.dir/all] Error 2
2015/02/20 00:32:38 - INFO: [package:run_job] gmake[1]: *** Waiting for unfinished jobs....
```
Can you post which git commit of Hashstack did you use and your build profile? It looks like the `-fPIC` might be missing, and we might have already fixed that (or maybe it's something else).

**Comment by cmaurini** [comment]
Hi @certik  I use this fork https://github.com/cmaurini/hashstack, which is currently up-to-date with master. You find below the profile, which is the `fenics-babbage2.yaml` on the fork.

Best,

Corrado.

```
extends:
- file: linux.yaml

parameters:
  HOST_MPICC: /share/apps/openmpi174_amd64_gcc482/bin/mpicc
  HOST_MPICXX: /share/apps/openmpi174_amd64_gcc482/bin/mpic++
  HOST_MPIF77: /share/apps/openmpi174_amd64_gcc482/bin/mpif77
  HOST_MPIF90: /share/apps/openmpi174_amd64_gcc482/bin/mpif90
  HOST_MPIEXEC: /share/apps/openmpi174_amd64_gcc482/bin/mpiexec
  HOST_CMAKE: /share/apps/openmpi174_amd64_gcc482/bin/cmake
  PETSC_ARCH: linux-gnu-cxx-opt
  PROLOGUE: source /share/users/common/HPC/lmod/lmod/init/profile; module load gcc openmpi_amd64/1.7.4 git;  module list; 

# The packages list specifies all the packages that you
# require installed.  <#> will ensure that all packages
# and their dependencies are installed when you build this
# profile.

packages:
  launcher:
  pcre:
  cmake:
  m4:
    use: host-m4
  python:
    host: false 
    build_with: |
      openssl, bzip2, sqlite
    link: shared
  mpi:
    use: host-mpi
  blas:
    use: openblas
  hdf5:
  parmetis:
    without_check: true
  petsc:
    build_with: |
       parmetis, openblas, scotch, suitesparse
    download: |
       superlu, ml,  superlu_dist, hypre, scalapack, blacs, mumps
    coptflags: -O2
    link: shared
    debug: false
  boost:
    toolset: gcc
    address_model: 64
  swig:
  pkg-config:
  ipython:
  matplotlib:
  fiat:
  ufl:
  uflacs:
  ffc:
  instant:
  mpi4py:
  slepc:
  petsc4py:
  slepc4py:
  vtk: 
  dolfin:
    build_with: |
      vtk, openblas,  parmetis,  suitesparse, scotch, petsc, petsc4py, slepc, slepc4py,  zlib, hdf5, bzip2
  mshr:
```

**Comment by certik** [comment]
Thank you. That looks good to me. @johannesring any ideas why this might fail?

**Comment by johannesring** [comment]
No, I'm not sure. Maybe a compiler issue? @cmaurini - you can try adding `-fPIC` to `CMAKE_C_FLAGS` and `CMAKE_CXX_FLAGS` in `vtk.yaml`:

    diff --git a/pkgs/vtk/vtk.yaml b/pkgs/vtk/vtk.yaml
    index cb70f2f..3164d24 100644
    --- a/pkgs/vtk/vtk.yaml
    +++ b/pkgs/vtk/vtk.yaml
    @@ -63,6 +63,8 @@ build_stages:
         - '-D CMAKE_INSTALL_RPATH:STRING="${ARTIFACT}/lib/vtk-5.10"'
         - '-D PYTHON_EXECUTABLE:FILEPATH="${PYTHON}"'
         - '-D VTK_USE_SYSTEM_TIFF:BOOL=ON'
    +    - '-D CMAKE_C_FLAGS:STRING=-fPIC'
    +    - '-D CMAKE_CXX_FLAGS:STRING=-fPIC'
     
     - when: vtk_use_tk
       name: configure

**Comment by cmaurini** [comment]
Thanks, I tried but I have the same error.

**Comment by johannesring** [comment]
The problem could be that it is trying to link with a static library. Could you try to add `-D CMAKE_VERBOSE_MAKEFILE:BOOL=ON` in `vtk.yaml` and post the `build.log`?

**Comment by cmaurini** [comment]
You can find here the full [build.log](http://www.lmm.jussieu.fr/~corrado/tmp/vtk-build.log)

This is the end:

```
[maurini@babbage2 vtk-4xcwmp6hxehi]$ tail build.log 
2015/02/22 13:36:59 - INFO: [package:run_job] cd /share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Widgets && /share/users/common/hashdist-packages/bld/cmake/nr6m776qcbof/bin/cmake -E cmake_link_script CMakeFiles/vtkWidgetsPythonD.dir/link.txt --verbose=1
2015/02/22 13:36:59 - INFO: [package:run_job] /share/apps/gcc/gcc482/bin/g++  -fPIC -fPIC  -Wno-deprecated -O3 -DNDEBUG  -L/share/users/common/hashdist-packages/bld/cmake/nr6m776qcbof/lib -Wl,-rpath=/share/users/common/hashdist-packages/bld/cmake/nr6m776qcbof/lib -L/share/users/common/hashdist-packages/bld/libtiff/glqlptoak4ih/lib -Wl,-rpath=/share/users/common/hashdist-packages/bld/libtiff/glqlptoak4ih/lib -L/share/users/common/hashdist-packages/bld/patchelf/5ilj4lwa7gsl/lib -Wl,-rpath=/share/users/common/hashdist-packages/bld/patchelf/5ilj4lwa7gsl/lib -L/share/users/common/hashdist-packages/bld/python/5ohagshsbza5/lib -Wl,-rpath=/share/users/common/hashdist-packages/bld/python/5ohagshsbza5/lib -L/share/users/common/hashdist-packages/bld/setuptools/v3fnpjocno4s/lib -Wl,-rpath=/share/users/common/hashdist-packages/bld/setuptools/v3fnpjocno4s/lib  -shared -Wl,-soname,libvtkWidgetsPythonD.so.5.10 -o ../bin/libvtkWidgetsPythonD.so.5.10.1 CMakeFiles/vtkWidgetsPythonD.dir/vtk3DWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkAbstractWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkAffineRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkAffineRepresentation2DPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkAffineWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkAngleRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkAngleRepresentation2DPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkAngleRepresentation3DPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkAngleWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkAxesTransformWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkAxesTransformRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkBalloonRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkBalloonWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkBezierContourLineInterpolatorPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkBiDimensionalRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkBiDimensionalRepresentation2DPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkBiDimensionalWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkBorderRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkBorderWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkBoundedPlanePointPlacerPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkBoxRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkBoxWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkBoxWidget2Python.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkBrokenLineWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkButtonRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkButtonWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkCameraRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkCameraWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkCaptionRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkCaptionWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkCellCentersPointPlacerPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkCenteredSliderRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkCenteredSliderWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkContinuousValueWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkContinuousValueWidgetRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkContourLineInterpolatorPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkContourRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkFocalPlaneContourRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkContourWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkCheckerboardRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkCheckerboardWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkConstrainedPointHandleRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkDijkstraImageContourLineInterpolatorPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkDistanceWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkDistanceRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkDistanceRepresentation2DPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkDistanceRepresentation3DPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkEllipsoidTensorProbeRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkEventPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkFixedSizeHandleRepresentation3DPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkFocalPlanePointPlacerPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkHandleRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkHandleWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkHoverWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkImageActorPointPlacerPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkImageCroppingRegionsWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkImageOrthoPlanesPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkImagePlaneWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkImageTracerWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkImplicitPlaneRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkImplicitPlaneWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkImplicitPlaneWidget2Python.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkLinearContourLineInterpolatorPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkLineRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkLineWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkLineWidget2Python.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkLogoRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkLogoWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkOrientationMarkerWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkOrientedGlyphContourRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkOrientedGlyphFocalPlaneContourRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkParallelopipedRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkParallelopipedWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkClosedSurfacePointPlacerPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkPlaneWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkPlaybackRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkPlaybackWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkPointHandleRepresentation2DPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkPointHandleRepresentation3DPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkPointPlacerPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkPointWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkPolyDataSourceWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkPolyDataPointPlacerPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkAbstractPolygonalHandleRepresentation3DPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkPolygonalHandleRepresentation3DPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkOrientedPolygonalHandleRepresentation3DPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkPolygonalSurfacePointPlacerPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkPolyDataContourLineInterpolatorPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkPolygonalSurfaceContourLineInterpolatorPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkProp3DButtonRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkRectilinearWipeRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkRectilinearWipeWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkResliceCursorThickLineRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkResliceCursorLineRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkResliceCursorRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkResliceCursorWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkResliceImageViewerPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkResliceImageViewerMeasurementsPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkScalarBarRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkScalarBarWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkSeedRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkSeedWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkSliderRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkSliderRepresentation2DPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkSliderRepresentation3DPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkSliderWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkSphereHandleRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkSphereRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkSphereWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkSphereWidget2Python.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkSplineRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkSplineWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkSplineWidget2Python.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkTensorProbeWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkTensorProbeRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkTerrainDataPointPlacerPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkTerrainContourLineInterpolatorPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkTextRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkTexturedButtonRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkTexturedButtonRepresentation2DPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkTextWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkWidgetCallbackMapperPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkWidgetEventPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkWidgetEventTranslatorPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkWidgetRepresentationPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkWidgetSetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkXYPlotWidgetPython.cxx.o CMakeFiles/vtkWidgetsPythonD.dir/vtkWidgetsPythonInit.cxx.o ../bin/libvtkWidgets.so.5.10.1 ../bin/libvtkPythonCore.so.5.10.1 ../bin/libvtkRenderingPythonD.so.5.10.1 ../bin/libvtkHybridPythonD.so.5.10.1 ../bin/libvtkVolumeRendering.so.5.10.1 ../bin/libvtkRenderingPythonD.so.5.10.1 ../bin/libvtkGraphicsPythonD.so.5.10.1 ../bin/libvtkImagingPythonD.so.5.10.1 ../bin/libvtkHybrid.so.5.10.1 ../bin/libvtkRendering.so.5.10.1 ../bin/libvtkGraphics.so.5.10.1 ../bin/libvtkImaging.so.5.10.1 ../bin/libvtkIOPythonD.so.5.10.1 ../bin/libvtkIO.so.5.10.1 ../bin/libvtkFilteringPythonD.so.5.10.1 ../bin/libvtkFiltering.so.5.10.1 ../bin/libvtkCommonPythonD.so.5.10.1 ../bin/libvtkPythonCore.so.5.10.1 ../bin/libvtkCommon.so.5.10.1 ../bin/libvtksys.so.5.10.1 -ldl -lm -Wl,-rpath,/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/bin:: -Wl,-rpath-link,/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/bin 
2015/02/22 13:37:00 - INFO: [package:run_job] cd /share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Widgets && /share/users/common/hashdist-packages/bld/cmake/nr6m776qcbof/bin/cmake -E cmake_symlink_library ../bin/libvtkWidgetsPythonD.so.5.10.1 ../bin/libvtkWidgetsPythonD.so.5.10 ../bin/libvtkWidgetsPythonD.so
2015/02/22 13:37:00 - INFO: [package:run_job] gmake[2]: Leaving directory `/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build'
2015/02/22 13:37:00 - INFO: [package:run_job] /share/users/common/hashdist-packages/bld/cmake/nr6m776qcbof/bin/cmake -E cmake_progress_report /share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/CMakeFiles  83 84 85 86
2015/02/22 13:37:00 - INFO: [package:run_job] [ 91%] Built target vtkWidgetsPythonD
2015/02/22 13:37:00 - INFO: [package:run_job] gmake[1]: Leaving directory `/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build'
2015/02/22 13:37:00 - INFO: [package:run_job] gmake: *** [all] Error 2
2015/02/22 13:37:00 - ERROR: [package:run_job] Command '[u'/bin/bash', '_hashdist/build.sh']' returned non-zero exit status 2
2015/02/22 13:37:00 - ERROR: [package:run_job] command failed (code=2); raising
```

**Comment by johannesring** [comment]
Sorry, I'm not sure where the problem is. Is it possible for you to try a different compiler?

**Comment by certik** [comment]
I extracted the relevant lines from the output:
```
2015/02/22 13:36:24 - INFO: [package:run_job] cd /share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Infovis && /share/apps/gcc/gcc482/bin/g++   -DVTK_IN_VTK -DvtkInfovis_EXPORTS -fPIC  -Wno-deprecated -O3 -DNDEBUG -fPIC -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Common -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/VolumeRendering -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Rendering -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Charts -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Chemistry -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/vtkalglib -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Wrapping/Python -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Wrapping/Python -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Infovis -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Geovis -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Views -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/VolumeRendering -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Hybrid -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Widgets -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Rendering -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Charts -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Chemistry -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Rendering/Testing/Cxx -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/IO -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Imaging -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Graphics -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/GenericFiltering -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Filtering -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Common -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Common/Testing/Cxx -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/vtknetcdf -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/vtknetcdf -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/vtknetcdf/include -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/vtklibproj4 -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/vtklibproj4 -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/DICOMParser -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/DICOMParser -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/vtkfreetype/include -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/vtkfreetype/include -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/LSDyna -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/LSDyna -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/MaterialLibrary -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/MaterialLibrary -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/vtkmetaio -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/vtkmetaio -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/verdict -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/verdict -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/vtkhdf5 -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/vtkhdf5 -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/vtkhdf5/src -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/vtkhdf5/src -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/vtkhdf5/hl/src -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/vtkhdf5/hl/src -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/utf8/source -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/vtkalglib -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/ftgl/src -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/ftgl -I/share/users/common/hashdist-packages/bld/libtiff/glqlptoak4ih/include -I/share/users/common/hashdist-packages/bld/python/5ohagshsbza5/include/python2.7    -fvisibility=hidden -fvisibility-inlines-hidden -o CMakeFiles/vtkInfovis.dir/vtkMultiCorrelativeStatistics.cxx.o -c /share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Infovis/vtkMultiCorrelativeStatistics.cxx
2015/02/22 13:36:46 - INFO: [package:run_job] cd /share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Widgets && /share/apps/gcc/gcc482/bin/g++   -DVTK_IN_VTK -DvtkWidgetsPythonD_EXPORTS -fPIC  -Wno-deprecated -O3 -DNDEBUG -fPIC -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Common -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/VolumeRendering -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Rendering -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Charts -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Chemistry -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/vtkalglib -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Wrapping/Python -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Wrapping/Python -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Infovis -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Geovis -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Views -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/VolumeRendering -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Hybrid -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Widgets -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Rendering -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Charts -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Chemistry -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Rendering/Testing/Cxx -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/IO -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Imaging -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Graphics -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/GenericFiltering -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Filtering -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Common -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Common/Testing/Cxx -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/vtknetcdf -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/vtknetcdf -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/vtknetcdf/include -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/vtklibproj4 -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/vtklibproj4 -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/DICOMParser -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/DICOMParser -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/vtkfreetype/include -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/vtkfreetype/include -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/LSDyna -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/LSDyna -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/MaterialLibrary -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/MaterialLibrary -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/vtkmetaio -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/vtkmetaio -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/verdict -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/verdict -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/vtkhdf5 -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/vtkhdf5 -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/vtkhdf5/src -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/vtkhdf5/src -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/vtkhdf5/hl/src -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/vtkhdf5/hl/src -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/utf8/source -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/vtkalglib -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/Utilities/ftgl/src -I/share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Utilities/ftgl -I/share/users/common/hashdist-packages/bld/libtiff/glqlptoak4ih/include -I/share/users/common/hashdist-packages/bld/python/5ohagshsbza5/include/python2.7    -o CMakeFiles/vtkWidgetsPythonD.dir/vtkConstrainedPointHandleRepresentationPython.cxx.o -c /share/users/common/hashdist-packages/tmp/vtk-4xcwmp6hxehi/_build/Widgets/vtkConstrainedPointHandleRepresentationPython.cxx
2015/02/22 13:36:46 - INFO: [package:run_job] /usr/bin/ld: CMakeFiles/vtkInfovis.dir/vtkMultiCorrelativeStatistics.cxx.o: relocation R_X86_64_PC32 against `_ZNSt6vectorIP12vtkDataArraySaIS1_EE13_M_insert_auxEN9__gnu_cxx17__normal_iteratorIPS1_S3_EERKS1_' can not be used when making a shared object; recompile with -fPIC
2015/02/22 13:36:46 - INFO: [package:run_job] /usr/bin/ld: final link failed: Bad value
2015/02/22 13:36:46 - INFO: [package:run_job] collect2: error: ld returned 1 exit status
```
Something is wrong with regards to `-fPIC`, possibly linking a static library by a mistake, or something, as the build seems to be using `-fPIC` for the file which fails (`vtkMultiCorrelativeStatistics.cxx`).

**Comment by certik** [comment]
@cmaurini can you post the contents of `/share/users/common/HPC/lmod/lmod/init/profile`?

**Comment by certik** [comment]
Here is a similar problem: http://public.kitware.com/pipermail/titan-developers/2011-February/001642.html, but they never reached a conclusion.  Essentially in that thread, they are also using `-fPIC` and not using any static library (which would have to be compiled with `-fPIC` in order to link into a shared library). Essentially, some file or library that we link with (could be systemwide) is not compiled with `-fPIC`, and we just need to figure out which one.

@cryos you replied in that thread --- do you remember what the correct fix was? We seem to be facing exactly the same problem here, and we can't figure it out. Any ideas how to debug this?

**Comment by cmaurini** [comment]
Nothing special in the file `/share/users/common/HPC/lmod/lmod/init/profile`

```
[maurini@babbage2 hashstack]$ more /share/users/common/HPC/lmod/lmod/init/profile
#!/bin/sh
# -*- shell-script -*-
########################################################################
#  This is the system wide source file for setting up
#  modules:
#
########################################################################

########################################################################
# The PATH variable must include the "lua" program
########################################################################

if [ -z "$USER_IS_ROOT" ]; then

  . /share/users/common/HPC/lmod/lmod/init/bash >/dev/null # Module Support

  if [ -z "$MODULEPATH_ROOT" ]; then
    PATH=/share/users/common/HPC/bin:$PATH
    export PATH


    USER=${USER-${LOGNAME}}  # make sure $USER is set
    export USER
    
    LMOD_sys=`uname`; export LMOD_sys
    
    LMOD_arch=`uname -m`
    if [ "x$LMOD_sys" = xAIX ]; then
      LMOD_arch=rs6k
    fi
    export LMOD_arch

    
    MODULEPATH_ROOT="/share/users/common/HPC/modulefiles_bb2"
    export MODULEPATH_ROOT
    # export MODULEPATH=$(/share/users/common/HPC/lmod/lmod/libexec/addto --append MODULEPATH $MODULEPATH_ROOT/$LMOD_sys $MODULEPATH_ROOT/Core)
    export MODULEPATH=$(/share/users/common/HPC/lmod/lmod/libexec/addto --append MODULEPATH $MODULEPATH_ROOT/$LMOD_sys/base $MODULEPATH_ROOT/Core)
    export BASH_ENV=/share/users/common/HPC/lmod/lmod/init/bash
  fi
fi
```

Maybe it may be useful to known that system is very. You find below  the gcc compiler of the distribution. The one I am using (gcc482) has been manually compiled by the sysadmin.

```
[maurini@babbage2 hashstack]$ gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-libgcj-multifile --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --enable-plugin --with-java-home=/usr/lib/jvm/java-1.4.2-gcj-1.4.2.0/jre --with-cpu=generic --host=x86_64-redhat-linux
Thread model: posix
gcc version 4.1.2 20080704 (Red Hat 4.1.2-44)
```

**Comment by cmaurini** [comment]
FYI: I can successfully compile the entire fenics stack when I disable vtk. So the problem is only with vtk. 

@johannesring how should I change my profile to build also gcc?  I tried adding 

```
gcc:
    host: false
```

but nothing change (does not compile gcc).

**Comment by cmaurini** [comment]
Update: using a profile with

```
gcc:
    host: false
```

it compiles `gcc` only after `vtk` (for reasons that I ignore) and `vtk` compiles successfully. I suppose that this means that the problem is using a non-system compiler for `vtk` on my system.

**Comment by johannesring** [comment]
@certik would be the one to ask about this, but basically you need to first build gcc with hashdist and then setup your profile to use this gcc.

**Comment by cmaurini** [comment]
Thanks, I solved by selectively using `gcc44` for vtk by adding the following lines to the `vtk.yaml`
```
    - '-D CMAKE_CXX_COMPILER=/usr/bin/g++44'
    - '-D CMAKE_C_COMPILER=/usr/bin/gcc44'
```

**Comment by certik** [comment]
@cmaurini so it looks like the gcc on your cluster might have some problems.

As to Hashdist's gcc, see the hashdist mailinglist, where I posted instructions.  Essentially just install `hd_base` from here:

https://gist.github.com/certik/db990b8260e77830fa48

and then reuse the `PROLOGUE` from `test.yaml`.

**Comment by cryos** [comment]
A little late, and I think you came to the right conclusion. We think it was a bug/interaction between the VTK libraries using Boost and the compiler. I think using a new compiler worked, but it was quite some time ago and I am struggling to remember now. We do not do a lot of testing on old GCC compilers, so some of these things get missed on the regular dashboard submissions.

**Comment by certik** [comment]
@cryos thank you for the comment. It looks like a similar problem was the cause here (the interaction of VTK and a particular compiler installation), since just changing the compiler helped.

However, I still don't understand technically what was the low level problem. In your experience, how exactly can some compiler installation fail like above? Could it be that perhaps, some parts (which ones?) that are provided by the gcc installation were not compiled with `-fPIC`?
